version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-home:/var/jenkins_home

volumes:
  jenkins-home:
